// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxttkxljrxsusawxjjro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4dHRreGxqcnhzdXNhd3hqanJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTI5MjQsImV4cCI6MjA2OTM2ODkyNH0.C2uV8BR1o8oaWrcbDyMoFYK3lZs8Bpqo9D9bvDyo7us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});